language: php

branches:
  only:
    - master

matrix:
  include:
    - php: 7.2
      dist: trusty
      sudo: required
    - php: 7.3
      dist: trusty
      sudo: required
    - php: hhvm
      dist: trusty
      sudo: required
    - php: nightly
      dist: trusty
      sudo: required

  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install
